export const questions = [
  {
    id: "1",
    type: "single-choice",
    content: "How many rings of power were made for the Elves, Dwarves, and Men?",
    possibleAnswers: [
      "Three for the Elves, Seven for Dwarves, and Nine for Men",
      "Two for Elves, Six for Dwarves, and Eleven for Men",
      "Six for Elves, Six for Dwarves, and Eleven for Men",
    ],
    correctAnswers: ["Three for the Elves, Seven for Dwarves, and Nine for Me"],
  },
  {
    id: "2",
    type: "single-choice",
    content: "The Lord of the Rings films are based on a novel written by which author?",
    possibleAnswers: ["Leonidas", "J. R. R. Tolkien", "A. A. Milne"],
    correctAnswers: ["J. R. R. Tolkien"],
  },
  {
    id: "3",
    type: "single-choice",
    content:
      "What is the name of the Elven character with the blonde hair and blue eyes who was lethal with a bow and charming with his looks?",
    possibleAnswers: ["Leonidas", "Mowgly", "Legolas"],
    correctAnswers: ["Legolas"],
  },
  {
    id: "4",
    type: "single-choice",
    content:
      "Who released King Theoden from the spell of Saruman, which caused his appearance to make him look much older than he is?",
    possibleAnswers: ["Gandalf", "Dumbledore", "Hagrid"],
    correctAnswers: ["Gandalf"],
  },
  {
    id: "5",
    type: "single-choice",
    content: "What is the name of the mountain where the Master Ring was made?",
    possibleAnswers: ["Mount Rushmore", "Mount Everest", "Mount Doom"],
    correctAnswers: ["Mount Doom"],
  },
  {
    id: "6",
    type: "single-choice",
    content: "Why do witchers carry two swords (steel and silver)?",
    possibleAnswers: [
      "The first is for humans, the second is for monsters",
      "The second is for monsters especially vulnerable to silver",
      "The second is for peeling apples",
    ],
    correctAnswers: ["The second is for monsters especially vulnerable to silver"],
  },
  {
    id: "7",
    type: "single-choice",
    content: "What is the name of the main character in Gothic from Piranha Bytes?",
    possibleAnswers: ["Robhar II", "Berengar", "He is nameless"],
    correctAnswers: ["He is nameless"],
  },
  {
    id: "8",
    type: "single-choice",
    content:
      "Which expansion pack for Final Fantasy XIV caused its servers to be overloaded at the end of 2021?",
    possibleAnswers: ["Endwalker", "Heavensward", "Shadowbringers"],
    correctAnswers: ["Endwalker"],
  },
  {
    id: "9",
    type: "single-choice",
    content:
      "What is the name of the song sung by bard Dandelion from the TV series adaptation of the Witcher, which conquered the Internet?",
    possibleAnswers: [
      "Bros before sorceresses",
      "Toss a coin to your Witcher",
      "Lambert, Lambert what a prick",
    ],
    correctAnswers: ["answer2"],
  },
  {
    id: "10",
    type: "single-choice",
    content: "What causes the Lumos spell from Harry Potter?",
    possibleAnswers: [
      "Reducing the person on whom it is thrown",
      "Opening the locked chest / door",
      "Blue light comes on and emits a slight heat",
    ],
    correctAnswers: ["Blue light comes on and emits a slight heat"],
  },
  {
    id: "11",
    type: "single-choice",
    content: "Who is the author of the novel Metro 2033?",
    possibleAnswers: ["Andrzej Sapkowski", "Borys Akunin", "Dmitry Glukhovsky"],
    correctAnswers: ["Dmitry Glukhovsky"],
  },
  {
    id: "12",
    type: "single-choice",
    content: "Where does the action of the Fallout 1 game released in 1977 take place?",
    possibleAnswers: ["Southern California", "West Virginia", "North Carolina"],
    correctAnswers: ["Southern California"],
  },
  {
    id: "13",
    type: "single-choice",
    content: "Who is the youngest of Ned Stark's children in Games of Thrones?",
    possibleAnswers: ["Bran", "Rickon", "Arya"],
    correctAnswers: ["Rickon"],
  },
  {
    id: "14",
    type: "single-choice",
    content: "How did Star Wars' character Princess Leia get her title of royalty?",
    possibleAnswers: [
      "She is the adopted daughter of Bail Organa and Queen Breha",
      "She is the daughter of Queen Katrina of the Geonosians",
      "A mocking nickname from Han Solo",
    ],
    correctAnswers: ["She is the adopted daughter of Bail Organa and Queen Breha"],
  },
  {
    id: "15",
    type: "single-choice",
    content: "Where does Yoda from Star Wars live when he first trains Luke Skywalker?",
    possibleAnswers: ["Hoth", "Coruscant", "Dagobah"],
    correctAnswers: ["Dagobah"],
  },
  {
    id: "16",
    type: "multiple-choice",
    content: "Which of the following is NOT a typical fantasy character?",
    possibleAnswers: ["Lawyer", "Goblin", "Ogre", "Burglar"],
    correctAnswers: ["Lawyer", "Burglar"],
  },
  {
    id: "17",
    type: "multiple-choice",
    content: "Which of the following is NOT a typical fantasy setting?",
    possibleAnswers: ["Argentina", "Mordor", "Sanok", "Narnia"],
    correctAnswers: ["Argentina", "Sanok"],
  },
  {
    id: "18",
    type: "multiple-choice",
    content: "Which of the following characters is part of the Wizarding World fictional universe?",
    possibleAnswers: ["Hermione Granger", "Professor Albus Dumbledore", "Frodo Baggins", "Gandalf"],
    correctAnswers: ["Hermione Granger", "Professor Albus Dumbledore"],
  },
  {
    id: "19",
    type: "multiple-choice",
    content: "What are the names of the Rings of Pawer from The Lord of The Rings?",
    possibleAnswers: ["Narya", "Narnia", "Nenya", "Noway"],
    correctAnswers: ["Narya", "Nenya"],
  },
  {
    id: "20",
    type: "multiple-choice",
    content: "What are the different Beings In Lord Of The Rings?",
    possibleAnswers: ["Databasers", "Programmers", "Elves", "Ents"],
    correctAnswers: ["Elves", "Ents"],
  },
  {
    id: "21",
    type: "multiple-choice",
    content: "Who was in Thorin's Company from the Middle-Earth mythology by J.R.R?",
    possibleAnswers: ["Dwalin", "Fili", "Garin", "Nori"],
    correctAnswers: ["Dwalin", "Fili", "Nori"],
  },
  {
    id: "22",
    type: "multiple-choice",
    content: "What are the three oldest Star Wars movies from the list mentioned below?",
    possibleAnswers: [
      "Attack of the Clones",
      "A New Hope",
      "The Empire Strikes Back",
      "Return of the Jedi",
    ],
    correctAnswers: ["A New Hope", "The Empire Strikes Back", "Return of the Jedi"],
  },
  {
    id: "23",
    type: "multiple-choice",
    content: "What are the characters that appeared in the novel Metro 2033?",
    possibleAnswers: ["Artyom", "Hunter", "Anna", "Vladimir"],
    correctAnswers: ["Artyom", "Hunter", "Anna", "Vladimir"],
  },
  {
    id: "24",
    type: "multiple-choice",
    content: "Which of the following are NOT a part of the game series S.T.A.L.K.E.R.?",
    possibleAnswers: ["Pure Sky", "Clear Sky", "Shadow of Chernobyl", "Call of Pripyat"],
    correctAnswers: ["Pure Sky"],
  },
  {
    id: "25",
    type: "multiple-choice",
    content: "What are the names of Daenerys' dragons from Games of Thrones?",
    possibleAnswers: ["Rhaegal", "Drogon", "Viserion", "Bisanton"],
    correctAnswers: ["Rhaegal", "Drogon", "Viserion"],
  },
  {
    id: "26",
    type: "multiple-choice",
    content: "Which of the following are NOT names of witchers from the Witcher Saga?",
    possibleAnswers: ["Lambert", "Coen", "Dijkstra", "Cahir"],
    correctAnswers: ["Dijkstra", "Cahir"],
  },
  {
    id: "27",
    type: "multiple-choice",
    content: "Which of the listed below are fantasy games?",
    possibleAnswers: ["Journey", "God of War", "Train Simulator 2022", "DiRT 3"],
    correctAnswers: ["Journey", "God of War"],
  },
  {
    id: "28",
    type: "multiple-choice",
    content: "Which of the following are names of Hogwart's Houses?",
    possibleAnswers: ["Gryffindor", "Ravenclaw", "Bumblebee", "Optimus Prime"],
    correctAnswers: ["Gryffindor", "Ravenclaw"],
  },
  {
    id: "29",
    type: "multiple-choice",
    content: "Which of the following are computer games with the dominant magic theme?",
    possibleAnswers: ["Magicka", "Magicka 2", "Pillars of Eternity", "The Sims 4"],
    correctAnswers: ["Magicka", "Magicka 2", "Pillars of Eternity"],
  },
  {
    id: "30",
    type: "multiple-choice",
    content: "What are the Marvel Universe movies?",
    possibleAnswers: ["Black Widow", "Fantastic Four", "The Suicide Squad", "Joker"],
    correctAnswers: ["Black Widow", "Fantastic Four"],
  },
  {
    id: "31",
    type: "true-false",
    content: "There are 4 movies in the Lord of the Rings series.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
  {
    id: "32",
    type: "true-false",
    content: "Hermione Granger was a Harry Potter girlfriend.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
  {
    id: "33",
    type: "true-false",
    content:
      'In "Harry Potter and the Chamber of Secrets", as many as 14 Ford England were destroyed in order to shoot the scene in which Harry and Ron crash into the Whomping Willow',
    possibleAnswers: ["true", "false"],
    correctAnswers: ["true"],
  },
  {
    id: "34",
    type: "true-false",
    content: "Fallout is a series of post-renaissance role-playing video games.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
  {
    id: "35",
    type: "true-false",
    content:
      "While the Star Wars' Jedi use a number of crystal colors for their lightsabers, the red color is preferred by the Sith.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["true"],
  },
  {
    id: "36",
    type: "true-false",
    content:
      'The Game of Thrones\' character Gregor "the Mountain" Clegane kill Oberyn Martell in their trial by cutting his head off.',
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
  {
    id: "37",
    type: "true-false",
    content:
      "Game of Thrones' character Arya Stark joins the band of assassins in Braavos named Faceless Men.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["true"],
  },
  {
    id: "38",
    type: "true-false",
    content:
      "Obi Wan Kenobi destroyed the Droid Control Ship when he accidentally activated a Naboo Fighter's Autopilot.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
  {
    id: "39",
    type: "true-false",
    content: "Aquaman is a character from DC Universe.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["true"],
  },
  {
    id: "40",
    type: "true-false",
    content: "DC's Universe Joker character's main power is unhuman speed.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
  {
    id: "41",
    type: "true-false",
    content: "Marvel's Universe Ant-Man character's main power is changing his size.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["true"],
  },
  {
    id: "42",
    type: "true-false",
    content: "Heihachi Mishima is one of the main characters in the Street Fighter game series.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
  {
    id: "43",
    type: "true-false",
    content: "Kazuya from the Tekken game series is the Heihachi's biological son.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["true"],
  },
  {
    id: "44",
    type: "true-false",
    content: "H. P. Lovecraft is the author of The Call of Cthulhu short story.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["true"],
  },
  {
    id: "45",
    type: "true-false",
    content:
      "Cthulhu is NOT considered to be a Great Old One within the pantheon of Lovecraftian cosmic entities.",
    possibleAnswers: ["true", "false"],
    correctAnswers: ["false"],
  },
];
